name = "alpacki"
version = "2.0.0"

description = "🦙 HPACK protocol (RFC 7541) for Gleam"
target = "erlang"
licenses = ["Apache-2.0"]
repository = { type = "github", user = "vshakitskiy", repo = "alpacki" }
links = [{ title = "RFC 7541", href = "http://www.rfc-editor.org/rfc/rfc7541.txt" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
